id: A80681840
base_file: f0E01.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:16:53.320515
  last_modified_at: 2022-06-11 13:16:53.320520
